language: php
php:
  - 7.3
services:
  - docker
before_install:
  - nvm install node 
  - cp .env.test .env
install:
  - docker-compose up -d
before_script:
  - npm install
  - composer install
script:
  - npx cypress run
  - ./vendor/bin/phpunit tests
