language: php
php:
  - 7.3
services:
  - docker
  - mysql
before_install:
  - nvm install node
  - mysql -e 'CREATE DATABASE travis;'
install:
  - cp .env.travis .env
before_script:
  - composer install
  - php artisan migrate
  - php artisan db:seed 
  - npm install
script:
  - ./vendor/bin/phpunit tests
