language: php
php:
  - 7.3
services:
  - docker
  - mysql
before_install:
  - nvm install node
  - mysql -e 'CREATE DATABASE testci;'
install:
  - cp .env.travis .env
before_script:
  - composer install
  - php artisan migrate
  - php artisan db:seed
  - npm install
  - php artisan serve &
script:
  - ./vendor/bin/phpunit tests
  - npx cypress run
