language: php
php:
  - 7.3
services:
  - docker
before_install:
  - nvm install node 
install:
  - docker-compose up -d
before_script:
  - npm install
  - mkdir -p storage
  - mkdir -p storage/app
  - mkdir -p storage/framework
  - mkdir -p storage/framework/sessions
  - mkdir -p storage/framework/cache
  - mkdir -p storage/framework/views
  - chmod 777 -R storage
  - chmod -R 777 *
script:
  - npx cypress run
  - ./vendor/bin/phpunit tests
