language: php
php:
  - 7.3
services:
  - docker
before_install:
  - nvm install node 
  - cp cypress.travis.json cypress.json
install:
  - php artisan serve &
before_script:
  - npm install
  - composer install
script:
  - npx cypress run
  - ./vendor/bin/phpunit tests
