language: php
php:
  - 7.3
services:
  - docker
before_install:
  - nvm install node 
install:
  - cp .env.test .env
before_script:
  - composer install
  - npm install
script:
  - ./vendor/bin/phpunit tests
