language: php
php:
  - 7.3
services:
  - mysql
before_install:
  - nvm install node
  - mysql -e 'CREATE DATABASE testci;'
  - cp .env.travis .env
  - rm cypress.json
  - cp cypress.json.travis cypress.json
install:
  - composer install
  - php artisan migrate
  - php artisan db:seed
  - npm install
before_script:
  - php artisan serve &
script:
  - ./vendor/bin/phpunit tests
  - npx cypress run
